<ADSWorkspace Revision="35" Version="100">
    <Workspace Name="">
        <LibraryDefs Name="lib.defs" />
        <ConfigFile Name="dds.cfg" />
        <ConfigFile Name="de_sim.cfg" />
        <ConfigFile Name="hpeesofsim.cfg" />
        <Log Name="netlist.log" />
        <Log Name="search_history.log" />
        <Preferences Name="layout.prf" />
        <Preferences Name="lownoiseamp_lib_lay.prf" />
        <Preferences Name="lownoiseamp_lib_sch.prf" />
        <Preferences Name="schematic.prf" />
        <Dataset Name="lnadesign.ds" />
        <Data_Files Name="lnadesign.ds" />
        <Data_Files Name="lnadesign_data\logFile.txt" />
        <Library Name="ads_standard_layers" />
        <Library Name="ads_schematic_layers" />
        <Library Name="empro_standard_layers" />
        <Library Name="ads_builtin" />
        <Library Name="ads_standard_layers_ic" />
        <Library Name="ads_schematic_layers_ic" />
        <Library Name="ads_schematic_ports_ic" />
        <Library Name="ads_rflib" />
        <Library Name="ads_sources" />
        <Library Name="ads_simulation" />
        <Library Name="ads_tlines" />
        <Library Name="ads_bondwires" />
        <Library Name="ads_datacmps" />
        <Library Name="ads_behavioral" />
        <Library Name="ads_textfonts" />
        <Library Name="ads_common_cmps" />
        <Library Name="ads_designs" />
        <Library Name="ads_verification_test_bench" />
        <Library Name="ads_pelib" />
        <Library Name="lownoiseamp_lib" />
        <Library Name="RF_Transistors" />
        <Folder Name="sec 1">
            <Cell Name="lownoiseamp_lib:dc" />
            <Cell Name="lownoiseamp_lib:stability" />
            <Cell Name="lownoiseamp_lib:stability network" />
            <Cell Name="lownoiseamp_lib:the bias network design" />
        </Folder>
        <Data_Display Name="dc.dds" />
        <Dataset Name="dc.ds" />
        <Data_Files Name="dc.ds" />
        <Data_Files Name="dc_data\logFile.txt" />
        <Dataset Name="stability.ds" />
        <Data_Files Name="stability.ds" />
        <Data_Files Name="stability_data\logFile.txt" />
        <Data_Display Name="stability.dds" />
        <Data_Files Name="dc_annotation\lownoiseamp_lib_stability_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\lownoiseamp_lib_stability_schematic\annotation_map.xml" />
        <Dataset Name="stability_network.ds" />
        <Data_Files Name="dc_annotation\lownoiseamp_lib_stability#20network_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\lownoiseamp_lib_stability#20network_schematic\annotation_map.xml" />
        <Data_Files Name="stability_network.ds" />
        <Data_Files Name="stability_network_data\logFile.txt" />
        <Data_Display Name="stability network.dds" />
        <Data_Display Name="the bias network design.dds" />
        <Preferences Name="ads_tlines_lay.prf" />
        <Dataset Name="the_bias_network_design.ds" />
        <Data_Files Name="the_bias_network_design.ds" />
        <Data_Files Name="the_bias_network_design_data\logFile.txt" />
        <Folder Name="sec 2">
            <Cell Name="lownoiseamp_lib:a_input match req" />
            <Cell Name="lownoiseamp_lib:b_input match req" />
        </Folder>
        <Data_Display Name="a_input match req.dds" />
        <Dataset Name="__simdata060074.ds" />
        <Dataset Name="a_input_match_req.ds" />
        <Data_Files Name="a_input_match_req.ds" />
        <Data_Files Name="a_input_match_req_data\logFile.txt" />
        <Data_Files Name="dc_annotation\lownoiseamp_lib_a_input#20match#20req_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\lownoiseamp_lib_a_input#20match#20req_schematic\annotation_map.xml" />
        <Data_Files Name="dc_annotation\lownoiseamp_lib_dc_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\lownoiseamp_lib_dc_schematic\annotation_map.xml" />
        <Data_Files Name="__simdata060074.ds" />
        <Data_Display Name="b_input match req.dds" />
        <Dataset Name="b_input_match_req.ds" />
        <Data_Files Name="b_input_match_req.ds" />
        <Data_Files Name="b_input_match_req_data\logFile.txt" />
        <Data_Files Name="dc_annotation\lownoiseamp_lib_b_input#20match#20req_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\lownoiseamp_lib_b_input#20match#20req_schematic\annotation_map.xml" />
        <Cell Name="lownoiseamp_lib:DA_SmithChartMatch1_a_input_match_req" />
        <Cell Name="lownoiseamp_lib:DA_SmithChartMatch1_b_input_match_req" />
        <Cell Name="lownoiseamp_lib:DA_SmithChartMatch2_a_input_match_req" />
        <Cell Name="lownoiseamp_lib:DA_SmithChartMatch2_b_input_match_req" />
        <Cell Name="lownoiseamp_lib:DA_SmithChartMatch_b_input_match_req" />
        <Folder Name="sec 3">
            <Cell Name="lownoiseamp_lib:input" />
        </Folder>
        <Folder Name="sec 4">
            <Cell Name="lownoiseamp_lib:input match" />
            <Cell Name="lownoiseamp_lib:output" />
            <Cell Name="lownoiseamp_lib:main" />
        </Folder>
        <Dataset Name="main.ds" />
        <Data_Files Name="main.ds" />
        <Data_Files Name="main_data\logFile.txt" />
        <Data_Display Name="main.dds" />
        <Data_Files Name="dc_annotation\lownoiseamp_lib_main_schematic\annotation_1.xml" />
        <Data_Files Name="dc_annotation\lownoiseamp_lib_main_schematic\annotation_map.xml" />
    </Workspace>
</ADSWorkspace>
